[package]
name = "nock07"
version = "0.1.0"
authors = ["yusuke-eto <eto.yusuke@moneyforward.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
